Terraform 1
Otus-DevOps-2023-03/mickpav_infra pull request #5
Opened 2023-07-29 11:38 UTC by mickpav

# Выполнено ДЗ "Практика IaC с использованием Terraform"

 - [x] Основное ДЗ
 - [x] Задания со **

## В процессе сделано:
 - Создано описание  ресурса для создания  VM в YC из bобраза, созданного в предыдущем ДЗ.
 - Выполнен вывод переменных (IP адрес ВМ) в консоль (файл outputs.tf).
 - Описаны провижинеры, скрипт развертывания, файл конфига сервися для деплоя  приложения на созданную ВМ.
 - Созданы конфигурационные файлы variables.tf, terraform.tfvars, terraform.tfvars.example, в которых заданы входные переменные
 - Создан ресурс для создания  балансировщика HTTP, который направляет трафик на развернутое приложение на ВМ (файл lb.tf). В файле outputs.tf добавлен вывод адреса балансировщика.
 - В код внесено описание еще одного  ресурса для создания еще одной ВМ, которая также добавлена  его в балансировщик.
 -  Проведено тестирование - при остановке на одной из ВМ сервиса (systemctl stop puma), приложение продолжает функционировать по адресу балансировщика. Файл outputs.tf изменен для вывода адреса второй ВМ

Проблемы данной конфигурации:
 - избыточный код,
 - при правке частей кода, относящихся к именам или адресам необходимо особое внимание.

- Реализовал вариант конфигурации с использованием количества ВМ через параметр ресурса count. Переменная count задается в параметрах со значением по умолчанию 1.  

## Для создания инфраструктуры  выполнить команды:
- terraform plan
- terraform apply

## Как проверить работоспособность:
 - открыть в браузере адрес HTTP балансировщика.
 -

2023-07-31 08:06 UTC, mrgreyves requested changes
Здравствуйте!)
Проверил ваше дз
Рекомендую свериться с результатами тестов
Поправьте все что не относится к терраформ коду
ДЗ отправляю на доработку

2023-07-31 15:49 UTC, mickpav commented
Владимир, здравствуйте!
Все перепроверил - ругается на 
 structure: Check repo structure (2 failed)
     ×  File .gitignore should exist
     expected File .gitignore to exist
     ×  File .gitignore content should match /\n\Z/
     expected nil to match /\n\Z/
Но проблема в том, что данный файл присутствует и его содержимое нормально читается

2023-08-01 18:12 UTC, mrgreyves requested changes
Здравствуйте!)
.gitignore должен находится в корне репозитория =)

2023-08-06 11:45 UTC, mrgreyves approved these changes
Здравствуйте!)
Вот теперь все круто =)

2023-08-06 12:53 UTC, merged